[mysql]
host="127.0.0.1"
port=3306
database="tiktok"
username="root"
password="1234"
charset="utf8"

[redis]
host="127.0.0.1"
port=6379

[server]
host="192.168.1.7"
port=8080

[static]
path="/home/abc/workspace/tiktok/static"
